
version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python3 app.py --host=0.0.0.0
    env_file:
      - dev.env
    volumes:
      - "./backend/src:/app"
    ports:
      - 5000:5000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/src"
      - "/frontend/node_modules"
    ports:
      - 3000:3000
    depends_on:
      - backend

  nginx:
    image: nginx:1.25
    container_name: nginx
    volumes:
        - ../:/var/www
        - ./nginx/nginx_dev.conf:/etc/nginx/conf.d/default.conf
    ports:
        - 80:80
    depends_on:
        - backend
        - frontend
