version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn -w 4 -b 0.0.0.0:5000 "app:create_app('dev')"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - dev.env
    volumes:
      - "./backend/src:/app"
    ports:
      - 5000:5000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/src"
      - "/frontend/node_modules"
    ports:
      - 3000:3000
    depends_on:
      - backend

  nginx:
    image: nginx:1.25
    container_name: nginx
    volumes:
      - ../:/var/www
      - ./nginx/nginx_dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    volumes:
      - ./data/db:/var/lib/mysql
      - ./backend/src/init_db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "db" ] # We'll wait until the DB is ready to accept connections to start up dependent services
      timeout: 20s
      retries: 10
