version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn -w 4 -b 0.0.0.0:5000 "app:create_app('dev')"
    depends_on:
      db:
        condition: service_healthy
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DB: ${DATABASE_DB}
      DATABASE_HOST: ${DATABASE_HOST}
      TEST_DATABASE_DB: ${TEST_DATABASE_DB}
      ENVIRONMENT: ${ENVIRONMENT}
    volumes:
      - "./backend/src:/app"
    ports:
      - 5000:5000

  nginx:
    image: nginx:1.25
    container_name: nginx
    volumes:
      - ../:/var/www
      - ./nginx/nginx_dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - backend

  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    volumes:
      - ./data/db:/var/lib/mysql
      - ./backend/src/init_db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ] # We'll wait until the DB is ready to accept connections to start up dependent services
      timeout: 20s
      retries: 10
