version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn -w 4 -b 0.0.0.0:5000 "app:create_app('dev')"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5000:5000

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - backend

  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    volumes:
      - ./backend/src/init_db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ] # We'll wait until the DB is ready to accept connections to start up dependent services
      timeout: 20s
      retries: 10
