name: Backend Checks

on: pull-request
  types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  build:
    if: '! github.event.pull_request.draft'
    name: merge checks 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Build
      run: |
        docker-compose -f docker-compose-dev-ga.yaml up --build -d
  
    - name: Run Tests
      run: |
        docker-compose -f docker-compose-dev-ga.yaml exec -T backend pip3 install pytest
        docker-compose -f docker-compose-dev.yaml exec -T backend python3 -m pytest

    - name: Print logs
      if: always()
      run: |
        docker ps -a
        df -h
        docker logs commonplace-public_db_1
        docker logs commonplace-public_backend_1

    - name: Cleanup
      if: always()
      run: docker-compose -f docker-compose-dev-ga.yaml down
